import { X, Zap, AlertCircle } from 'lucide-react';
import { vh } from '../lib/viewport';

function parseSummary(text) {
  const lines = text.split('\n').map(l => l.trim()).filter(Boolean);
  const sections = [];
  for (const line of lines) {
    if (line.startsWith('###')) continue;
    if (line.startsWith('>')) {
      const clean = line.replace(/^>\s*/, '').replace(/\*\*/g, '');
      const colon = clean.indexOf(':');
      if (colon > -1) sections.push({ type: 'note', label: clean.slice(0, colon).trim(), value: clean.slice(colon + 1).trim() });
      continue;
    }
    const match = line.match(/^\*\*(.+?):\*\*\s*(.*)/);
    if (match) { sections.push({ type: 'field', label: match[1].trim(), value: match[2].trim() || '—' }); continue; }
    sections.push({ type: 'text', value: line.replace(/\*\*/g, '') });
  }
  return sections;
}

const FIELD_COLORS = {
  '👤': { color: '#2563eb', bg: '#eff6ff', border: '#bfdbfe' },
  '🛍': { color: '#7c3aed', bg: '#f5f3ff', border: '#ddd6fe' },
  '🛍️':{ color: '#7c3aed', bg: '#f5f3ff', border: '#ddd6fe' },
  '💰': { color: '#059669', bg: '#ecfdf5', border: '#a7f3d0' },
  '📋': { color: '#d97706', bg: '#fffbeb', border: '#fde68a' },
  '📍': { color: '#0891b2', bg: '#ecfeff', border: '#a5f3fc' },
  '✅': { color: '#059669', bg: '#f0fdf4', border: '#bbf7d0' },
  '📝': { color: '#b45309', bg: '#fffbeb', border: '#fde68a' },
};
const DEFAULT_COLOR = { color: '#475569', bg: '#f8fafc', border: '#e2e8f0' };

function getColor(label) {
  return FIELD_COLORS[[...label][0]] || DEFAULT_COLOR;
}

const FULL_WIDTH = ['stage', 'suggested', 'next step', 'note', 'recommendation'];
const isFull = label => FULL_WIDTH.some(k => label.toLowerCase().includes(k));

export default function SummaryPanel({ summary, loading, onClose }) {
  if (!summary && !loading) return null;

  const sections = summary ? parseSummary(summary) : [];
  const fields = sections.filter(s => s.type === 'field');
  const notes  = sections.filter(s => s.type === 'note');
  const texts  = sections.filter(s => s.type === 'text');

  return (
    <div style={s.backdrop} onClick={onClose}>
      <div style={s.modal} className="summary-card" onClick={e => e.stopPropagation()}>

        <div style={s.header}>
          <div style={s.headerLeft}>
            <div style={s.headerIcon}><Zap size={18} color="#059669" /></div>
            <div>
              <p style={s.headerTitle}>AI Chat Summary</p>
              <p style={s.headerSub}>Generated by Claude · Internal only</p>
            </div>
          </div>
          <button style={s.closeBtn} onClick={onClose}><X size={16} /></button>
        </div>

        <div style={s.body}>
          {loading ? (
            <div style={s.loadingWrap}>
              <div className="summary-spinner" />
              <p style={s.loadingText} className="pulse-text">Analysing conversation…</p>
              <p style={s.loadingHint}>This takes a few seconds</p>
            </div>
          ) : (
            <>
              {fields.length > 0 && (
                <div style={s.grid}>
                  {fields.map((f, i) => {
                    const c = getColor(f.label);
                    const full = isFull(f.label);
                    return (
                      <div key={i} style={{
                        ...s.card, gridColumn: full ? '1 / -1' : 'span 1',
                        background: c.bg, border: `1px solid ${c.border}`,
                      }}>
                        <span style={{ ...s.cardLabel, color: c.color }}>{f.label}</span>
                        <p style={s.cardValue}>{f.value}</p>
                      </div>
                    );
                  })}
                </div>
              )}

              {notes.map((n, i) => {
                const c = getColor(n.label);
                return (
                  <div key={i} style={{ ...s.card, ...s.noteCard, background: c.bg, border: `1px solid ${c.border}`, marginBottom: 8 }}>
                    <span style={{ ...s.cardLabel, color: c.color }}>{n.label}</span>
                    <p style={s.cardValue}>{n.value}</p>
                  </div>
                );
              })}

              {fields.length === 0 && notes.length === 0 && texts.map((t, i) => (
                <p key={i} style={s.plainText}>{t.value}</p>
              ))}

              <div style={s.footer}>
                <AlertCircle size={12} color="#94a3b8" />
                <span style={s.footerText}>AI-generated — verify before acting</span>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

const s = {
  backdrop: {
    position: 'fixed', inset: 0,
    background: 'rgba(15,23,42,0.4)',
    backdropFilter: 'blur(4px)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    zIndex: 100, padding: 20,
  },
  modal: {
    background: '#ffffff', borderRadius: 16,
    width: '100%', maxWidth: 560, maxHeight: vh(82),
    display: 'flex', flexDirection: 'column',
    overflow: 'hidden',
    boxShadow: '0 20px 60px rgba(0,0,0,0.15), 0 0 0 1px rgba(0,0,0,0.05)',
  },
  header: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '18px 20px', borderBottom: '1px solid #e2e8f0',
  },
  headerLeft: { display: 'flex', alignItems: 'center', gap: 12 },
  headerIcon: {
    width: 38, height: 38, borderRadius: 10,
    background: '#ecfdf5', border: '1px solid #a7f3d0',
    display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
  },
  headerTitle: { fontSize: 15, fontWeight: 700, color: '#0f172a', margin: 0 },
  headerSub: { fontSize: 11, color: '#94a3b8', margin: '2px 0 0' },
  closeBtn: {
    background: '#f1f5f9', border: 'none', cursor: 'pointer',
    width: 30, height: 30, borderRadius: 7,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    color: '#64748b',
  },
  body: { padding: '18px 20px', overflowY: 'auto', flex: 1 },
  loadingWrap: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: '36px 0' },
  loadingText: { fontSize: 14, fontWeight: 600, color: '#0f172a' },
  loadingHint: { fontSize: 12, color: '#94a3b8' },
  grid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, marginBottom: 8 },
  card: {
    borderRadius: 10, padding: '12px 14px',
    display: 'flex', flexDirection: 'column', gap: 5,
  },
  noteCard: { marginBottom: 0 },
  cardLabel: { fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em' },
  cardValue: { fontSize: 13, fontWeight: 500, color: '#0f172a', lineHeight: 1.5, margin: 0 },
  plainText: { fontSize: 13, color: '#475569', lineHeight: 1.7, marginBottom: 8 },
  footer: {
    display: 'flex', alignItems: 'center', gap: 6,
    marginTop: 14, paddingTop: 12, borderTop: '1px solid #e2e8f0',
  },
  footerText: { fontSize: 11, color: '#94a3b8' },
};
